development:
  availability_url: https://www.sawaisp.sy/whatsappapi/check_availability.php?phone_number=%{phone}
test:
  availability_url: https://www.sawaisp.sy/whatsappapi/check_availability.php?phone_number=%{phone}
production:
  availability_url: https://www.sawaisp.sy/whatsappapi/check_availability.php?phone_number=%{phone}