cc: countrycode without 00 or +, e.g: 963
phone: phone number with country code but without 00 or +, ex: 963987654321
password: password, see http://hacktracking.blogspot.de/2013/02/yowsup-cli-send-whatsapp-messages-from.html to learn more